options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'transformer'
      - '--gen2'
      - '--runtime=python312'
      - '--region=europe-west1'
      - '--entry-point=main'
      - '--source=.'
      - '--trigger-http'
      - '--no-allow-unauthenticated'
      - '--memory=256Mi'
      - '--timeout=300s'
